### ISSUE TITLE
CAS is not working properly

### ISSUE THREAD

**Issue by ykadowak** [kpango/gache#134]
This should pass but fails with `CAS failed`.

```go
func TestSwapThenCAS(t *testing.T) {
    syncMap := sync.Map{}
    syncMap.Store("", interface{}(nil))
    swapped1 := syncMap.CompareAndSwap("", interface{}(nil), 42)

    gacheMap := Map[string, any]{}
    gacheMap.Store("", interface{}(nil))
    swappe2 := gacheMap.CompareAndSwap("", interface{}(nil), 42)

    if swapped1 != swappe2 {
        t.Error("CAS failed")
    }
}
```

**Comment by ykadowak** [comment]
Edited the test case (replace Swap with Store)

**Comment by ykadowak** [comment]
Even this fails so this seems more like a bug if I'm using this library correctly.

```go
func TestStoreThenCAS(t *testing.T) {
    gacheMap := Map[string, any]{}
    gacheMap.Store("", 21)
    swapped := gacheMap.CompareAndSwap("", 21, 42)

    if !swapped {
        t.Error("CompareAndSwap failed")
    }
}
```

**Comment by kpango** [comment]
@ykadowak CAS has been modified by the following PR and I would like to separate out the impact of this modification.
https://github.com/kpango/gache/pull/133

Can you try to do the same test using v2.0.6?

**Comment by ykadowak** [comment]
v2.0.6 seems to work properly

**Comment by kpango** [comment]
Got it, I'll revert #133 and make new release.

Thank you.

**Comment by kpango** [comment]
@ykadowak I've just released v2.0.9.
Please check it.

**Comment by ykadowak** [comment]
Confirmed it's fixed. Thanks.

IMHO, it should be considered to add [upstream tests](https://go.dev/src/sync/map_test.go) and run it between `sync.Map` and `gache.Map`. Benchmarking does not prove that it's working as expected.

**Comment by kpango** [comment]
@ykadowak Thank you for suggestion.
I've added test code for map.go at commit https://github.com/kpango/gache/commit/4b8b60addf57dba1b150ca01a3ac51115627a355
