### ISSUE TITLE
Maybe we do not need a global instance of gache?

### ISSUE THREAD

**Issue by kevindiu** [kpango/gache#80]
Same as topic.
https://github.com/kpango/gache/blob/b5c48d4d0d8d9ac4627363e87be351a2dab3cf96/gache.go#L89

**Comment by kevindiu** [comment]
or maybe we can just remove init() function?

**Comment by kpango** [comment]
I think we can remove init function.
But if we delete init function user should call GetGache function to use gache's global instance. May be it makes some problem for current user

**Comment by kpango** [comment]
If we do that we have to publish this release as a major release.
I prefer left init function for backward compatibility

**Comment by kevindiu** [comment]
Lets wait for golang2 generic support and include this change together 😁
